error: Derive PartialEq for NumericError
This makes it easy to pick out particular errors. Not deriving Eq
because at some point we might make this enum backed, and then Other
would be != Other.