Cargo.toml: Subtly update required Rust version
Rust 1.77 (but not nightly) insist that:

> error: the `cargo::` syntax for build script output instructions was
> added in Rust 1.77.0, but the minimum supported Rust version of
> `riot-wrappers v0.8.999 (/__w/rust-riot-wrappers/rust-riot-wrappers)`
> is 1.77.