Create an `rust_eh_personality` symbol rather than attempting to populate the lang item
The lang item has long been unused and unusable in RIOT Rust setups; the
new version can solve the linker issues ("undefined reference to
`rust_eh_personality'") that pop up in some applications on native.